# Generated by Django 5.0.6 on 2024-05-28 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_instructor_learner'),
        ('rate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='instructor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='base.instructor'),
        ),
    ]
