# Generated by Django 4.2.13 on 2024-07-06 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0003_enrollcourse_delete_learnercourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_update', models.CharField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enroll_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='course.enrollcourse')),
            ],
        ),
    ]
