# Generated by Django 5.0.6 on 2024-06-24 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('payment', '0001_initial'),
        ('slot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_on', models.DateTimeField(auto_created=True, auto_now=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='base.instructor')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='base.learner')),
                ('payment', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='payment.payment')),
                ('slot', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='slot.slot')),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
    ]
