# Generated by Django 5.0.6 on 2024-05-29 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_book_slot_alter_book_instructor_alter_book_learner_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='booking',
            table='bookings',
        ),
    ]
