# Generated by Django 5.0.6 on 2024-06-27 06:56

import django.db.models.deletion
import slot.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0007_alter_licenseinformation_issuing_authority_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(validators=[slot.validators.validate_start_time])),
                ('duration', models.IntegerField(choices=[(30, '30 minutes'), (60, '1 hour'), (90, '1.5 hours'), (120, '2 hours')], default=60)),
                ('is_booked', models.BooleanField(default=False)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_slots', to='base.instructor')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='base.school')),
            ],
            options={
                'ordering': ['school', 'start_time', 'instructor'],
            },
        ),
        migrations.AddConstraint(
            model_name='slot',
            constraint=models.UniqueConstraint(fields=('school', 'instructor', 'start_time'), name='unique_instructor_slot'),
        ),
    ]
