# Generated by Django 4.2.13 on 2024-07-05 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_licenseinformation_issuing_authority_and_more'),
        ('slot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slot',
            options={'ordering': ['start_time', 'instructor']},
        ),
        migrations.RemoveConstraint(
            model_name='slot',
            name='unique_instructor_slot',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='school',
        ),
        migrations.AddField(
            model_name='slot',
            name='learner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='base.learner'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='slot',
            constraint=models.UniqueConstraint(fields=('instructor', 'start_time'), name='unique_instructor_slot'),
        ),
    ]
