# Generated by Django 5.0.6 on 2024-05-30 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0002_alter_slot_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
