# Generated by Django 4.2.13 on 2024-07-19 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_activationmailhistory'),
        ('slot', '0002_alter_slot_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='learner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='base.learner'),
        ),
    ]
