# Generated by Django 4.2.13 on 2024-07-19 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_activationmailhistory'),
        ('slot', '0003_alter_slot_learner'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='base.school'),
        ),
    ]
