# Generated by Django 5.0.6 on 2024-05-31 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0003_slot_is_booked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slot',
            old_name='datetime',
            new_name='slot_start',
        ),
    ]
