# Generated by Django 4.2.13 on 2024-08-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_review_learner'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('school', 'learner'), name='one_learner_review_per_school'),
        ),
    ]
