# Generated by Django 5.0.6 on 2024-05-29 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0003_user_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.IntegerField(choices=[(1, 'Credit Card'), (2, 'Debit Card'), (3, 'Cash')])),
                ('created_on', models.DateTimeField(auto_created=True)),
                ('learner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='base.learner')),
            ],
        ),
    ]
