# Generated by Django 4.2.13 on 2024-07-05 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('base', '0007_alter_licenseinformation_issuing_authority_and_more'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentDetails',
            new_name='PaymentDetail',
        ),
    ]
