# Generated by Django 5.0.6 on 2024-05-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_payment_learner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='created_on',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
