# Generated by Django 4.2.13 on 2024-07-15 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_enrollcourse_payment'),
        ('base', '0007_alter_licenseinformation_issuing_authority_and_more'),
        ('payment', '0003_remove_paymentdetail_course_paymentdetail_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetail',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='course.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='learner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='base.learner'),
        ),
    ]
