# Generated by Django 5.0.6 on 2024-05-29 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0003_user_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('make', models.IntegerField(choices=[(1, 'Motorbike'), (2, 'Car'), (3, 'Truck')])),
                ('instructor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='base.instructor')),
            ],
        ),
    ]
