# Generated by Django 5.0.6 on 2024-06-24 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(blank=True, default='')),
                ('model', models.CharField(default='XXXXX', max_length=50)),
                ('make', models.IntegerField(choices=[(1, 'Motorbike'), (2, 'Car'), (3, 'Truck')])),
                ('type', models.IntegerField(choices=[(1, 'Manual'), (2, 'Automatic')], default=1)),
                ('license_no', models.CharField(default='XX000000', max_length=10)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='base.instructor')),
            ],
        ),
    ]
