# Generated by Django 5.0.6 on 2024-06-25 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_instructor_area_of_expertise'),
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='instructor',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='base.school'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='license_no',
            field=models.CharField(default='XX000000', max_length=15),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='make',
            field=models.CharField(choices=[('motorbike', 'Motorbike'), ('car', 'Car'), ('truck', 'Truck')]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')]),
        ),
    ]
