# Generated by Django 5.0.6 on 2024-06-26 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_remove_vehicle_instructor_vehicle_school_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='license_no',
            new_name='plate_no',
        ),
    ]
