# Generated by Django 5.0.6 on 2024-06-01 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_alter_vehicle_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='license_no',
            field=models.CharField(default='XX000000', max_length=10),
        ),
    ]
