# Generated by Django 4.2.13 on 2024-08-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_rename_license_no_vehicle_plate_no'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(fields=('plate_no',), name='unique_plate_no'),
        ),
    ]
