# Generated by Django 5.0.6 on 2024-06-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_vehicle_image_url_alter_vehicle_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(default='XXXXX', max_length=50),
        ),
    ]
