# Generated by Django 5.0.6 on 2024-06-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_alter_vehicle_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='type',
            field=models.IntegerField(choices=[(1, 'Manual'), (2, 'Automatic')], default=1),
        ),
    ]
