# Generated by Django 5.0.6 on 2024-05-29 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_location'),
        ('book', '0002_initial'),
        ('payment', '0002_alter_payment_learner'),
        ('slot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='slot.slot'),
        ),
        migrations.AlterField(
            model_name='book',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='base.instructor'),
        ),
        migrations.AlterField(
            model_name='book',
            name='learner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='base.learner'),
        ),
        migrations.AlterField(
            model_name='book',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='payment.payment'),
        ),
    ]
