# Generated by Django 5.0.6 on 2024-05-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_book_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='booked_on',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
