# Generated by Django 5.0.6 on 2024-06-01 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chat',
            new_name='ChatHistory',
        ),
    ]
