# Generated by Django 5.0.6 on 2024-06-01 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_chat_chathistory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatHistory',
            new_name='Chat',
        ),
    ]
