version: '3'

services:
  pc_app:
    image: ayush/project-cemphris:v0 # correct db url in this image
    ports:
      - "8000:8000"
    networks:
      - project-cemphris-network
    depends_on:
      - pc_db
    # command: sh -c 'python manage.py migrate'
    #apt-get update;apt-get install cron;echo "*/5 * * * * root /usr/bin/python3 /app/manage.py process_scheduled_emails" >> /etc/crontab;'
  
  pc_db:
    image: postgres:15.7
    ports:
      - "5432:5432"
    networks:
      - project-cemphris-network
    environment:
      POSTGRES_DB: project_cemphris
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qweasd123

networks:
  project-cemphris-network:
    driver: bridge
