# Generated by Django 5.0.6 on 2024-06-24 08:04

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(blank=True, default='')),
                ('profile_completion_level', models.IntegerField(choices=[(1, 'Basic'), (2, 'Intermediate'), (3, 'Complete')], default=1)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('role', models.CharField(choices=[('learner', 'Learner'), ('instructor', 'Instructor'), ('school', 'School')], default='learner', max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='XYZ', max_length=255)),
                ('location', models.CharField(blank=True, max_length=2000, null=True)),
                ('image_url', models.URLField(blank=True, default='')),
                ('mobile_number', models.CharField(default='0000000000', max_length=20, null=True)),
                ('preferred_language', models.CharField(default='English', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LicenseInformation',
            fields=[
                ('number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('image_url', models.URLField(blank=True, default='')),
                ('type', models.IntegerField(choices=[(1, 'Learner'), (2, 'Lmv'), (3, 'Transport'), (4, 'Hmv'), (5, 'Hazardous'), (6, 'Motorcycle'), (7, 'Tractor'), (8, 'Ntv'), (9, 'Idp')])),
                ('expiration_date', models.DateField()),
                ('issuing_authority', models.IntegerField(choices=[(1, 'State Transport Department'), (2, 'Regional Transport Office'), (3, 'Ut Transport Department'), (4, 'Ministry Of Road Transport And Highways')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='license', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('location', models.CharField(blank=True, max_length=2000, null=True)),
                ('image_url', models.URLField(blank=True, default='')),
                ('mobile_number', models.CharField(default='0000000000', max_length=20, null=True)),
                ('preferred_language', models.CharField(default='English', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='XYZ', max_length=255)),
                ('location', models.CharField(blank=True, max_length=2000, null=True)),
                ('image_url', models.URLField(blank=True, default='')),
                ('mobile_number', models.CharField(default='0000000000', max_length=20, null=True)),
                ('preferred_language', models.CharField(default='English', null=True)),
                ('experience', models.IntegerField(default=0, null=True)),
                ('area_of_expertise', models.IntegerField(choices=[(1, 'Motorbike'), (2, 'Car'), (3, 'Truck')], null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructors', to='base.school')),
            ],
        ),
    ]
