# Generated by Django 5.0.6 on 2024-06-25 05:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_learner_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_completion_level',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
