# Generated by Django 5.0.6 on 2024-05-30 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='learner',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='instructor',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='base.instructor'),
        ),
        migrations.AddField(
            model_name='user',
            name='learner',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='base.learner'),
        ),
    ]
