# Generated by Django 5.0.6 on 2024-05-30 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_instructor_user_remove_learner_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='instructor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='base.instructor'),
        ),
        migrations.AlterField(
            model_name='user',
            name='learner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='base.learner'),
        ),
    ]
