# Generated by Django 5.0.6 on 2024-06-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_user_profile_completion_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='area_of_expertise',
            field=models.IntegerField(choices=[('motorbike', 'Motorbike'), ('car', 'Car'), ('truck', 'Truck')], null=True),
        ),
    ]
