# Generated by Django 5.0.6 on 2024-05-30 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_user_instructor_alter_user_learner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='learner',
        ),
        migrations.AddField(
            model_name='instructor',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learner',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='learner', to=settings.AUTH_USER_MODEL),
        ),
    ]
