# Generated by Django 5.0.6 on 2024-06-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_instructor_area_of_expertise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseinformation',
            name='issuing_authority',
            field=models.CharField(choices=[('state_transport_department', 'State Transport Department'), ('regional_transport_office', 'Regional Transport Office (RTO)'), ('ut_transport_department', 'Union Territory Transport Department'), ('morth', 'Ministry of Road Transport and Highways (MoRTH)')]),
        ),
        migrations.AlterField(
            model_name='licenseinformation',
            name='type',
            field=models.CharField(choices=[('learner', "Learner's License"), ('lmv', 'Light Motor Vehicle License'), ('transport', 'Transport Vehicle License'), ('hmv', 'Heavy Motor Vehicle License'), ('hazardous', 'Hazardous Goods License'), ('motorcycle', 'Motorcycle License'), ('tractor', 'Tractor License'), ('ntv', 'Non-Transport Vehicle License'), ('idp', 'International Driving Permit')]),
        ),
    ]
