# Generated by Django 5.0.6 on 2024-06-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_user_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_completion_level',
            field=models.IntegerField(choices=[(40, 'Basic'), (70, 'Intermediate'), (100, 'Complete')], default=40),
        ),
    ]
