# Generated by Django 4.2.13 on 2024-07-17 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='desc',
            field=models.TextField(blank=True, default=''),
        ),
    ]
