# Generated by Django 5.0.6 on 2024-06-02 10:32

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_user_profile_completion_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='area_of_expertise',
            field=models.IntegerField(choices=[(1, 'Motorbike'), (2, 'Car'), (3, 'Truck')], null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='experience',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(default=datetime.datetime(2024, 6, 2, 10, 32, 11, 466583, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(default='0000000000', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(default='English', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_completion_level',
            field=models.IntegerField(choices=[(1, 'Basic'), (2, 'Intermediate'), (3, 'Complete')], default=1),
        ),
        migrations.CreateModel(
            name='LicenseInformation',
            fields=[
                ('number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('image_url', models.URLField(blank=True, default='')),
                ('type', models.IntegerField(choices=[(1, 'Learner'), (2, 'Lmv'), (3, 'Transport'), (4, 'Hmv'), (5, 'Hazardous'), (6, 'Motorcycle'), (7, 'Tractor'), (8, 'Ntv'), (9, 'Idp')])),
                ('expiration_date', models.DateField()),
                ('issuing_authority', models.IntegerField(choices=[(1, 'State Transport Department'), (2, 'Regional Transport Office'), (3, 'Ut Transport Department'), (4, 'Ministry Of Road Transport And Highways')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='license', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
