# Generated by Django 4.2.13 on 2024-08-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_activationmailhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='desc',
            field=models.TextField(blank=True, default=''),
        ),
    ]
