# Generated by Django 5.0.6 on 2024-06-02 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_user_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dob',
        ),
    ]
