# Generated by Django 5.0.6 on 2024-06-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_remove_instructor_organisation_instructor_school_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='preferred_language',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='instructor',
            name='full_name',
            field=models.CharField(default='XYZ', max_length=255),
        ),
        migrations.AddField(
            model_name='learner',
            name='full_name',
            field=models.CharField(default='XYZ', max_length=255),
        ),
        migrations.AddField(
            model_name='learner',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='learner',
            name='location',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='learner',
            name='mobile_number',
            field=models.CharField(default='0000000000', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='learner',
            name='preferred_language',
            field=models.CharField(default='English', null=True),
        ),
    ]
