# Generated by Django 4.2.13 on 2024-08-12 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_enrollcourse_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='enrollcourse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 7, 29, 15, 29, 15, 516337, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollcourse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_content',
            field=models.JSONField(blank=True),
        ),
    ]
